Bump to jenkins:2.6.4 and use upstream helm repo instead of default helm repo
mesosphere/kubeaddons-enterprise pull request #94
Opened 2020-11-10 19:05 UTC by takirala

With current settings, the jenkins chart install is crashlooping kubeaddons controller with:
```
2020-11-10T18:45:38.523Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "kubeaddons.mesosphere.io", "reconcilerKind": "Addon", "controller": "addon", "name": "jenkins", "namespace": "kudo-test-superb-anemone", "error": "deploy error: chart \"jenkins\" matching 1.9.4 not found in stable index. (try 'helm repo update'): no chart name found", "
```

2020-11-10 19:07 UTC, takirala commented
This was bumped to be in sync with https://github.com/mesosphere/dcos-migration/tree/main/jenkins

2020-11-11 07:29 UTC, DominikDary approved these changes

2020-11-12 08:45 UTC, DominikDary commented
@chhsia0 can you please review this PR?

2020-11-12 10:58 UTC, juliangieseke reviewed
couple things:

* `catalog.kubeaddons.mesosphere.io/addon-revision`, `appversion.kubeaddons.mesosphere.io/jenkins` and `values.chart.helm.kubeaddons.mesosphere.io/jenkins` need to be updated to the new version as well
* I _think_ in this repo, we usually create new folders per version, so I guess this PR should add a `2.x` folder instead of changing the `1.x` folder (see cassandra for an example) - or at least rename it.
* `1.x` folder probably also needs an update to point to the new repo, given default repos will go offline, correct?

Caveat: Im not 100% sure if the above is still up to date or if this repo has changed something recently.

2020-11-12 11:14 UTC, shaneutt requested changes
> couple things:
> 
>     * `catalog.kubeaddons.mesosphere.io/addon-revision`, `appversion.kubeaddons.mesosphere.io/jenkins` and `values.chart.helm.kubeaddons.mesosphere.io/jenkins` need to be updated to the new version as well
> 
>     * I _think_ in this repo, we usually create new folders per version, so I guess this PR should add a `2.x` folder instead of changing the `1.x` folder (see cassandra for an example) - or at least rename it.
> 
>     * `1.x` folder probably also needs an update to point to the new repo, given default repos will go offline, correct?
> 
> 
> Caveat: Im not 100% sure if the above is still up to date or if this repo has changed something recently.

All of this is correct. This repo relies on multiple revision files present so that the Kommander Catalog UI can list and search the history of changes, we'll need to make a separate file (you can make the separate directory as well, but that's not something the catalog cares about that's just helpful for the human reading the repo) and update the relevant annotations as Julian mentioned.

2020-11-20 15:08 UTC, DominikDary commented
I think this is obsolete right now due to the fact the the suggested changes have been implemented with https://github.com/mesosphere/kubeaddons-enterprise/pull/95.
@takirala what do you think?

2020-11-20 17:52 UTC, vinodkone commented
Let's close this in favor of #95

2020-11-20 18:00 UTC, closed without merging